# Auto-generated by AI-Playground
# Generated: 2025-12-30T20:34:38.782829
# Experiment: House Price Prediction

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)


# ============================================================================
# DATA SPLITTING
# ============================================================================

def split_data(df: pd.DataFrame, target_column: str, test_size: float = 0.2):
    """
    Split data into train and test sets.
    
    Args:
        df: Input DataFrame
        target_column: Name of target column
        test_size: Proportion of data for testing
    
    Returns:
        X_train, X_test, y_train, y_test
    """
    print(f"Splitting data (test_size={test_size})...")
    
    # Separate features and target
    X = df.drop(columns=[target_column])
    y = df[target_column]
    
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=RANDOM_STATE,
        
    )
    
    print(f"Training set: {len(X_train)} samples")
    print(f"Test set: {len(X_test)} samples")
    
    return X_train, X_test, y_train, y_test

# Assuming df is already loaded and preprocessed
# X_train, X_test, y_train, y_test = split_data(df, 'price')


# ============================================================================
# MODEL TRAINING
# ============================================================================

def train_model(X_train, y_train):
    """
    Train LinearRegression model.
    
    Args:
        X_train: Training features
        y_train: Training target
    
    Returns:
        Trained model
    """
    print("Training LinearRegression...")
    print(f"Features: {X_train.shape[1]}")
    print(f"Samples: {len(X_train)}")
    
    # Initialize model
    model = LinearRegression(
        
        random_state=RANDOM_STATE
    )
    
    # Train model
    model.fit(X_train, y_train)
    
    # Training metrics
    train_score = model.score(X_train, y_train)
    print(f"Training score: {train_score:.4f}")
    
    return model

# Train the model
# model = train_model(X_train, y_train)


# ============================================================================
# MODEL SAVING
# ============================================================================

def save_model(model, filepath: str = 'model.pkl'):
    """
    Save trained model to file.
    
    Args:
        model: Trained model
        filepath: Path to save model
    """
    print(f"Saving model to {filepath}...")
    
    with open(filepath, 'wb') as f:
        pickle.dump(model, f)
    
    print(f"Model saved successfully!")

# Save the model
# save_model(model)
