# Auto-generated by AI-Playground
# Generated: 2025-12-30T21:33:31.958217
# Experiment: CSV Data Processing

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split


from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer



import pickle
import json
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)


# ============================================================================
# DATA LOADING
# ============================================================================

def load_data(file_path: str) -> pd.DataFrame:
    """
    Load dataset from file.
    
    Args:
        file_path: Path to the dataset file
    
    Returns:
        Loaded DataFrame
    """
    print(f"Loading data from {file_path}...")
    
    
    df = pd.read_csv(file_path)
    
    
    print(f"Loaded {len(df)} rows and {len(df.columns)} columns")
    print(f"Columns: {list(df.columns)}")
    
    return df


# Load the dataset
df = load_data('data.csv')

# Display basic information
print("\nDataset Info:")
print(df.info())
print("\nFirst few rows:")
print(df.head())
print("\nBasic statistics:")
print(df.describe())


# ============================================================================
# DATA PREPROCESSING
# ============================================================================

def preprocess_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply preprocessing steps to the dataset.
    
    Args:
        df: Input DataFrame
    
    Returns:
        Preprocessed DataFrame
    """
    df = df.copy()
    print("\nApplying preprocessing steps...")
    
    
    # Step 1: Missing Value Imputation
    print(f"  - Impute missing values using mean strategy")
    
    # Handle missing values in value
    from sklearn.impute import SimpleImputer
    imputer = SimpleImputer(strategy='mean')
    df[['value']] = imputer.fit_transform(df[['value']])
    
    
    
    
    
    print(f"Preprocessing complete. Shape: {df.shape}")
    return df


# Apply preprocessing
df = preprocess_data(df)