"""
Main Pipeline Script - Customer Churn Prediction

This script orchestrates the complete ML pipeline by importing
the generated preprocessing and training modules.

Auto-generated by AI-Playground
"""

import pandas as pd
import numpy as np
from pathlib import Path

# Import generated modules
from preprocess import preprocess_data
from train import split_data, train_model, save_model, load_model, predict

# Configuration
DATA_PATH = 'customer_data.csv'
MODEL_PATH = 'models/churn_model.pkl'
RANDOM_STATE = 42

def main():
    """Run the complete ML pipeline."""
    print("=" * 80)
    print("Customer Churn Prediction Pipeline")
    print("=" * 80)
    
    # Step 1: Load data
    print("\n[1/5] Loading data...")
    df = pd.read_csv(DATA_PATH)
    print(f"Loaded {len(df)} rows, {len(df.columns)} columns")
    
    # Step 2: Preprocess data
    print("\n[2/5] Preprocessing data...")
    df_processed = preprocess_data(df)
    print(f"Processed shape: {df_processed.shape}")
    
    # Step 3: Split data
    print("\n[3/5] Splitting data...")
    X_train, X_test, y_train, y_test = split_data(df_processed, target_column='churn')
    print(f"Train: {len(X_train)} samples, Test: {len(X_test)} samples")
    
    # Step 4: Train model
    print("\n[4/5] Training model...")
    model = train_model(X_train, y_train, verbose=True)
    
    # Step 5: Evaluate and save
    print("\n[5/5] Evaluating and saving model...")
    test_score = model.score(X_test, y_test)
    print(f"Test score: {test_score:.4f}")
    
    # Save model
    save_model(model, MODEL_PATH)
    
    # Make predictions
    predictions = predict(model, X_test)
    print(f"\nGenerated {len(predictions)} predictions")
    
    print("\n" + "=" * 80)
    print("Pipeline completed successfully!")
    print("=" * 80)


def predict_new_data(data_path: str, model_path: str = MODEL_PATH):
    """
    Load a trained model and make predictions on new data.
    
    Args:
        data_path: Path to new data CSV
        model_path: Path to saved model
    
    Returns:
        Predictions array
    """
    print(f"Loading model from {model_path}...")
    model = load_model(model_path)
    
    print(f"Loading data from {data_path}...")
    df = pd.read_csv(data_path)
    
    print("Preprocessing data...")
    df_processed = preprocess_data(df)
    
    print("Making predictions...")
    predictions = predict(model, df_processed)
    
    return predictions


if __name__ == '__main__':
    main()
