"""
Training Module - Customer Churn Prediction

Auto-generated by AI-Playground
Generated: 2025-12-30T20:49:10.381395
Model: RandomForestClassifier

This module can be imported and used in other scripts:
    from train import train_model, save_model, load_model
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle
from pathlib import Path
from typing import Tuple, Optional
import warnings
warnings.filterwarnings('ignore')

# Configuration
RANDOM_STATE = 42
TEST_SIZE = 0.2
MODEL_PATH = 'models/churn_model.pkl'

# Set random seed
np.random.seed(RANDOM_STATE)


def split_data(
    df: pd.DataFrame,
    target_column: str = 'churn',
    test_size: float = TEST_SIZE
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
    """
    Split data into train and test sets.
    
    Args:
        df: Input DataFrame
        target_column: Name of target column
        test_size: Proportion of data for testing
    
    Returns:
        X_train, X_test, y_train, y_test
    """
    X = df.drop(columns=[target_column])
    y = df[target_column]
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=RANDOM_STATE,
        stratify=y,
    )
    
    return X_train, X_test, y_train, y_test


def create_model():
    """
    Create and return a new model instance.
    
    Returns:
        Initialized model
    """
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        min_samples_split=5,
        random_state=RANDOM_STATE
    )
    return model


def train_model(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_val: Optional[pd.DataFrame] = None,
    y_val: Optional[pd.Series] = None,
    verbose: bool = True
):
    """
    Train RandomForestClassifier model.
    
    Args:
        X_train: Training features
        y_train: Training target
        X_val: Validation features (optional)
        y_val: Validation target (optional)
        verbose: Whether to print training progress
    
    Returns:
        Trained model
    """
    if verbose:
        print(f"Training {context['model_class']}...")
        print(f"Features: {X_train.shape[1]}")
        print(f"Samples: {len(X_train)}")
    
    # Create and train model
    model = create_model()
    model.fit(X_train, y_train)
    
    # Training metrics
    if verbose:
        train_score = model.score(X_train, y_train)
        print(f"Training score: {train_score:.4f}")
        
        if X_val is not None and y_val is not None:
            val_score = model.score(X_val, y_val)
            print(f"Validation score: {val_score:.4f}")
    
    return model


def save_model(model, filepath: str = MODEL_PATH) -> None:
    """
    Save trained model to file.
    
    Args:
        model: Trained model
        filepath: Path to save model
    """
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    
    with open(filepath, 'wb') as f:
        pickle.dump(model, f)
    
    print(f"Model saved to {filepath}")


def load_model(filepath: str = MODEL_PATH):
    """
    Load trained model from file.
    
    Args:
        filepath: Path to load model from
    
    Returns:
        Loaded model
    """
    with open(filepath, 'rb') as f:
        model = pickle.load(f)
    
    print(f"Model loaded from {filepath}")
    return model


def predict(model, X: pd.DataFrame) -> np.ndarray:
    """
    Make predictions using trained model.
    
    Args:
        model: Trained model
        X: Features to predict on
    
    Returns:
        Predictions
    """
    return model.predict(X)


if __name__ == '__main__':
    """
    Example usage when run as a script.
    """
    print("=" * 80)
    print("Training Module - Customer Churn Prediction")
    print("=" * 80)
    
    # Example: Load your data here
    # df = pd.read_csv('your_data.csv')
    
    # Split data
    # X_train, X_test, y_train, y_test = split_data(df)
    
    # Train model
    # model = train_model(X_train, y_train)
    
    # Save model
    # save_model(model)
    
    # Make predictions
    # predictions = predict(model, X_test)
    
    print("\nTo use this module in another script:")
    print("  from train import train_model, save_model, load_model, predict")
